# Generated by Django 6.0.5 on 2026-06-28 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=4, unique=True)),
                ('rfc', models.CharField(max_length=13)),
                ('razon_social', models.CharField(max_length=200)),
                ('regimen_fiscal', models.CharField(max_length=3)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('cert_path', models.CharField(max_length=500)),
                ('key_path', models.CharField(max_length=500)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración Fiscal',
                'verbose_name_plural': 'Configuraciones Fiscales',
            },
        ),
        migrations.CreateModel(
            name='CatalogoSAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogo', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('vigente', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Catálogo SAT',
                'verbose_name_plural': 'Catálogos SAT',
                'ordering': ['catalogo', 'clave'],
                'unique_together': {('catalogo', 'clave')},
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('nivel', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('A', 'Activo'), ('P', 'Pasivo'), ('C', 'Capital'), ('I', 'Ingreso'), ('G', 'Gasto')], max_length=1)),
                ('es_hoja', models.BooleanField(default=True)),
                ('naturaleza', models.CharField(choices=[('D', 'Deudora'), ('A', 'Acreedora')], max_length=1)),
                ('codigo_agrupador_sat', models.CharField(blank=True, max_length=10)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='finanzas.cuentacontable')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'ordering': ['numero'],
            },
        ),
    ]
