# Generated by Django 6.0.5 on 2026-06-28 00:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('referencias', '0010_add_fecha_captura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolizaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('D', 'Diario'), ('H', 'Ingreso'), ('E', 'Egreso')], max_length=1)),
                ('fecha', models.DateField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('concepto', models.CharField(max_length=300)),
                ('cerrado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas', to='referencias.referencia')),
            ],
            options={
                'verbose_name': 'Póliza Contable',
                'verbose_name_plural': 'Pólizas Contables',
                'ordering': ['-fecha', '-numero'],
                'unique_together': {('numero', 'tipo', 'anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='GastoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FLETE', 'Flete'), ('ALMACENAJE', 'Almacenaje'), ('DERECHOS', 'Derechos aduanales'), ('HONORARIOS', 'Honorarios agencia'), ('MANIOBRAS', 'Maniobras'), ('OTROS', 'Otros')], max_length=20)),
                ('concepto', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('num_factura_proveedor', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuenta_gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_referencia', to='finanzas.cuentacontable')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_finanzas', to='referencias.referencia')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL)),
                ('poliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='finanzas.polizacontable')),
            ],
            options={
                'verbose_name': 'Gasto de Referencia',
                'verbose_name_plural': 'Gastos de Referencia',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Anticipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('forma_pago', models.CharField(max_length=2)),
                ('num_operacion', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuenta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anticipos_destino', to='finanzas.cuentacontable')),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anticipos', to='referencias.referencia')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anticipos_registrados', to=settings.AUTH_USER_MODEL)),
                ('poliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anticipos', to='finanzas.polizacontable')),
            ],
            options={
                'verbose_name': 'Anticipo',
                'verbose_name_plural': 'Anticipos',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartidaPoliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.PositiveSmallIntegerField()),
                ('concepto', models.CharField(max_length=300)),
                ('debe', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('haber', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.cuentacontable')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='finanzas.polizacontable')),
            ],
            options={
                'verbose_name': 'Partida de Póliza',
                'verbose_name_plural': 'Partidas de Póliza',
                'ordering': ['linea'],
                'unique_together': {('poliza', 'linea')},
            },
        ),
    ]
