# Generated by Django 6.0.5 on 2026-06-28 00:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_polizacontable_gastoreferencia_anticipo_and_more'),
        ('referencias', '0010_add_fecha_captura'),
    ]

    operations = [
        migrations.CreateModel(
            name='XMLProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_fiscal', models.UUIDField(unique=True)),
                ('fecha_emision', models.DateTimeField()),
                ('rfc_emisor', models.CharField(max_length=13)),
                ('nombre_emisor', models.CharField(max_length=200)),
                ('rfc_receptor', models.CharField(max_length=13)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('tipo_comprobante', models.CharField(max_length=1)),
                ('concepto_principal', models.CharField(blank=True, max_length=300)),
                ('xml_file', models.FileField(upload_to='xmls_proveedores/%Y/%m/')),
                ('cargado_en', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xmls_proveedor', to='referencias.referencia')),
            ],
            options={
                'verbose_name': 'XML de Proveedor',
                'verbose_name_plural': 'XMLs de Proveedor',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.AddField(
            model_name='gastoreferencia',
            name='xml_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='finanzas.xmlproveedor'),
        ),
    ]
