# Generated by Django 6.0.5 on 2026-06-28 14:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_xmlproveedor_gastoreferencia_xml_proveedor'),
        ('referencias', '0010_add_fecha_captura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(default='A', max_length=10)),
                ('folio', models.PositiveIntegerField()),
                ('fecha_emision', models.DateTimeField(blank=True, null=True)),
                ('rfc_receptor', models.CharField(max_length=13)),
                ('nombre_receptor', models.CharField(max_length=200)),
                ('domicilio_fiscal_receptor', models.CharField(max_length=5)),
                ('regimen_fiscal_receptor', models.CharField(max_length=3)),
                ('uso_cfdi', models.CharField(default='G03', max_length=3)),
                ('forma_pago', models.CharField(default='99', max_length=2)),
                ('metodo_pago', models.CharField(default='PPD', max_length=3)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('uuid_fiscal', models.UUIDField(blank=True, null=True, unique=True)),
                ('xml_timbrado', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('TIMBRADA', 'Timbrada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('configuracion_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='finanzas.configuracionfiscal')),
                ('referencias', models.ManyToManyField(blank=True, related_name='facturas', to='referencias.referencia')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-created_at'],
                'unique_together': {('serie', 'folio')},
            },
        ),
        migrations.CreateModel(
            name='ConceptoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_prod_serv', models.CharField(default='84111506', max_length=8)),
                ('clave_unidad', models.CharField(default='ACT', max_length=3)),
                ('descripcion', models.CharField(max_length=1000)),
                ('cantidad', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14)),
                ('objeto_imp', models.CharField(default='02', max_length=2)),
                ('tasa_iva', models.DecimalField(decimal_places=4, default=Decimal('0.16'), max_digits=5)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='finanzas.factura')),
            ],
            options={
                'verbose_name': 'Concepto de Factura',
                'verbose_name_plural': 'Conceptos de Factura',
            },
        ),
    ]
