# Generated by Django 6.0.5 on 2026-06-28 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_factura_conceptofactura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('forma_pago', models.CharField(max_length=2)),
                ('num_operacion', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('TIMBRADO', 'Timbrado')], default='PENDIENTE', max_length=10)),
                ('uuid_fiscal', models.UUIDField(blank=True, null=True, unique=True)),
                ('xml_timbrado', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctoRelacionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_parcialidad', models.PositiveSmallIntegerField(default=1)),
                ('imp_saldo_anterior', models.DecimalField(decimal_places=2, max_digits=14)),
                ('imp_pagado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('imp_saldo_insoluto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_pago', to='finanzas.factura')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='finanzas.pago')),
            ],
            options={
                'verbose_name': 'Documento Relacionado',
                'verbose_name_plural': 'Documentos Relacionados',
            },
        ),
    ]
