# Generated by Django 6.0.5 on 2026-06-28 18:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_pago_doctorelacionado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('banco', models.CharField(max_length=50)),
                ('numero_cuenta', models.CharField(max_length=30)),
                ('clabe', models.CharField(blank=True, max_length=18)),
                ('moneda', models.CharField(default='MXN', max_length=3)),
                ('activa', models.BooleanField(default=True)),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_bancarias', to='finanzas.cuentacontable')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['banco', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=300)),
                ('referencia_banco', models.CharField(blank=True, max_length=100)),
                ('cargo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('abono', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('conciliado', models.BooleanField(default=False)),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='finanzas.cuentabancaria')),
                ('poliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_bancarios', to='finanzas.polizacontable')),
            ],
            options={
                'verbose_name': 'Movimiento Bancario',
                'verbose_name_plural': 'Movimientos Bancarios',
                'ordering': ['fecha', 'pk'],
            },
        ),
    ]
