# Generated by Django 6.0.5 on 2026-06-28 18:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_cuentabancaria_movimientobancario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('patente', models.CharField(max_length=4)),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('total_polizas', models.PositiveIntegerField(default=0)),
                ('total_facturas_emitidas', models.PositiveIntegerField(default=0)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_egresos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_anticipos_recibidos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('cerrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_mensuales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre Mensual',
                'verbose_name_plural': 'Cierres Mensuales',
                'ordering': ['-anio', '-mes', 'patente'],
                'unique_together': {('mes', 'anio', 'patente')},
            },
        ),
    ]
