# Generated by Django 6.0.5 on 2026-06-28 19:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_cierremensual'),
        ('referencias', '0010_add_fecha_captura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_operacion', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tasa_comision', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6)),
                ('monto_comision', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comisiones', to=settings.AUTH_USER_MODEL)),
                ('referencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comision', to='referencias.referencia')),
            ],
            options={
                'verbose_name': 'Comisión por Referencia',
                'verbose_name_plural': 'Comisiones por Referencia',
                'ordering': ['-anio', '-mes', 'referencia'],
            },
        ),
    ]
