# Generated by Django 6.0.5 on 2026-07-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_comisionreferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlproveedor',
            name='estado_asignacion',
            field=models.CharField(choices=[('ASIGNADO', 'Asignado'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='xmlproveedor',
            name='motivo_pendiente',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='xmlproveedor',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='xmls_proveedores/%Y/%m/'),
        ),
    ]
