# Generated by Django 6.0.5 on 2026-07-09 17:15

from django.db import migrations


def marcar_asignados(apps, schema_editor):
    XMLProveedor = apps.get_model('finanzas', 'XMLProveedor')
    XMLProveedor.objects.filter(referencia__isnull=False).update(
        estado_asignacion='ASIGNADO'
    )


def revertir(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_xmlproveedor_estado_asignacion_and_more'),
    ]

    operations = [
        migrations.RunPython(marcar_asignados, revertir),
    ]
