# Generated by Django 6.0.5 on 2026-07-11 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0010_asignar_estado_xml_existentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordatorioCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('15d', '15 días'), ('30d', '30 días'), ('60d', '60 días'), ('manual', 'Manual')], max_length=6)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('error_msg', models.TextField(blank=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='finanzas.factura')),
            ],
            options={
                'verbose_name': 'Recordatorio de Cobranza',
                'verbose_name_plural': 'Recordatorios de Cobranza',
                'ordering': ['-enviado_en'],
            },
        ),
    ]
