# Generated by Django 6.0.5 on 2026-07-12 03:17

import hal9mil.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_recordatoriocobranza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmlproveedor',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=hal9mil.storage_backends.media_storage, upload_to='xmls_proveedores/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='xmlproveedor',
            name='xml_file',
            field=models.FileField(storage=hal9mil.storage_backends.media_storage, upload_to='xmls_proveedores/%Y/%m/'),
        ),
    ]
