# Generated by Django 6.0.5 on 2026-07-14 15:35

import django.db.models.deletion
import django.utils.timezone
import hal9mil.storage_backends
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0012_media_storage_callable'),
        ('referencias', '0010_add_fecha_captura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCuentaGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerrada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota', models.CharField(blank=True, max_length=300)),
                ('reabierta_en', models.DateTimeField(blank=True, null=True)),
                ('cerrada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_cg', to=settings.AUTH_USER_MODEL)),
                ('reabierta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reaperturas_cg', to=settings.AUTH_USER_MODEL)),
                ('referencia', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cierre_cg', to='referencias.referencia')),
            ],
            options={
                'verbose_name': 'Cierre de cuenta de gastos',
                'verbose_name_plural': 'Cierres de cuenta de gastos',
            },
        ),
        migrations.CreateModel(
            name='NotificacionCuentaGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(max_length=254)),
                ('cc', models.EmailField(blank=True, max_length=254)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('LEIDO', 'Leído'), ('REBOTADO', 'Rebotado'), ('ERROR', 'Error')], default='ENVIADO', max_length=10)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('leido_en', models.DateTimeField(blank=True, null=True)),
                ('sg_message_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('error_msg', models.TextField(blank=True)),
                ('es_reenvio', models.BooleanField(default=False)),
                ('zip_file', models.FileField(blank=True, null=True, storage=hal9mil.storage_backends.media_storage, upload_to='cuentas_gastos/%Y/%m/')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_cg_enviadas', to=settings.AUTH_USER_MODEL)),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones_cg', to='referencias.referencia')),
            ],
            options={
                'verbose_name': 'Notificación de cuenta de gastos',
                'verbose_name_plural': 'Notificaciones de cuenta de gastos',
                'ordering': ['-enviado_en'],
            },
        ),
    ]
