# Generated by Django 6.0.5 on 2026-07-15 21:41

import django.db.models.deletion
import hal9mil.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0013_cierrecuentagastos_notificacioncuentagastos'),
        ('referencias', '0010_add_fecha_captura'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplementoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_complemento', models.UUIDField(unique=True)),
                ('uuid_factura_relacionada', models.UUIDField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField()),
                ('rfc_emisor', models.CharField(max_length=13)),
                ('nombre_emisor', models.CharField(max_length=200)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda_pago', models.CharField(default='MXN', max_length=3)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('IDENTIFICADO', 'Identificado'), ('REVISION', 'Requiere revisión')], default='PENDIENTE', max_length=12)),
                ('xml_file', models.FileField(storage=hal9mil.storage_backends.media_storage, upload_to='complementos_pago/%Y/%m/')),
                ('pdf_file', models.FileField(blank=True, null=True, storage=hal9mil.storage_backends.media_storage, upload_to='complementos_pago/%Y/%m/')),
                ('cargado_en', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complementos_pago', to='finanzas.xmlproveedor')),
                ('referencia_sugerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complementos_pago_sugeridos', to='referencias.referencia')),
            ],
            options={
                'verbose_name': 'Complemento de Pago',
                'verbose_name_plural': 'Complementos de Pago',
                'ordering': ['-cargado_en'],
            },
        ),
    ]
