# Generated by Django 6.0.5 on 2026-05-12 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_refe', models.CharField(db_index=True, max_length=50, unique=True)),
                ('patente', models.CharField(db_index=True, max_length=10)),
                ('prefijo', models.CharField(max_length=10)),
                ('cve_cliente', models.CharField(blank=True, max_length=20)),
                ('nombre_cliente', models.CharField(blank=True, db_index=True, max_length=255)),
                ('fecha_arribo', models.DateField(blank=True, null=True)),
                ('fecha_validacion', models.DateField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, db_index=True, null=True)),
                ('num_pedimento', models.CharField(blank=True, db_index=True, max_length=30)),
                ('clave_pedimento', models.CharField(blank=True, max_length=10)),
                ('tipo_pedimento', models.CharField(blank=True, max_length=10)),
                ('aduana', models.CharField(blank=True, max_length=10)),
                ('regimen', models.CharField(blank=True, max_length=10)),
                ('es_rectificacion', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_pago', 'num_refe'],
                'indexes': [models.Index(fields=['fecha_pago', 'patente'], name='referencias_fecha_p_ee8280_idx'), models.Index(fields=['patente', 'fecha_pago'], name='referencias_patente_53f398_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuiaBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.CharField(max_length=60)),
                ('tipo_guia', models.CharField(default='M', max_length=5)),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='referencias.referencia')),
            ],
            options={
                'unique_together': {('referencia', 'numero_guia')},
            },
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cont', models.CharField(max_length=20)),
                ('tipo', models.CharField(blank=True, max_length=10)),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenedores', to='referencias.referencia')),
            ],
            options={
                'unique_together': {('referencia', 'num_cont')},
            },
        ),
    ]
