# Generated by Django 6.0.5 on 2026-05-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='cve_capturista',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='referencia',
            name='linea_captura',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='referencia',
            name='nombre_capturista',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
