# Generated by Django 6.0.5 on 2026-05-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0002_add_linea_captura_capturista'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='num_operacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='linea_captura',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
