# Generated by Django 6.0.5 on 2026-05-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0003_rename_linea_add_num_operacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patente', models.CharField(db_index=True, max_length=10)),
                ('agent_id', models.CharField(default='unknown', max_length=50)),
                ('referencias', models.IntegerField(default=0)),
                ('contenedores', models.IntegerField(default=0)),
                ('guias', models.IntegerField(default=0)),
                ('creadas', models.IntegerField(default=0)),
                ('actualizadas', models.IntegerField(default=0)),
                ('exitoso', models.BooleanField(db_index=True, default=True)),
                ('error', models.TextField(blank=True)),
                ('duracion_seg', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Log de sincronización',
                'verbose_name_plural': 'Logs de sincronización',
                'ordering': ['-timestamp'],
            },
        ),
    ]
