# Generated by Django 6.0.5 on 2026-05-30 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0004_add_logsync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='fir_elec',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='GlosaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_conclusion', models.DateTimeField(blank=True, null=True)),
                ('nota', models.TextField(blank=True)),
                ('referencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='glosa', to='referencias.referencia')),
                ('usuario_conclusion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glosas_concluidas', to=settings.AUTH_USER_MODEL)),
                ('usuario_entrada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glosas_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de glosa',
                'verbose_name_plural': 'Registros de glosa',
                'ordering': ['-fecha_entrada'],
            },
        ),
    ]
