# Generated by Django 6.0.5 on 2026-05-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0005_add_fir_elec_and_glosa_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='glosaregistro',
            name='urgente',
            field=models.BooleanField(default=False),
        ),
    ]
