# Generated by Django 6.0.5 on 2026-06-02 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0006_glosaregistro_urgente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glosaregistro',
            name='referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosas', to='referencias.referencia'),
        ),
    ]
