# Generated by Django 6.0.5 on 2026-06-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0007_glosaregistro_onetomany'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='num_partidas',
            field=models.IntegerField(default=0),
        ),
    ]
