# Generated by Django 6.0.5 on 2026-06-03 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0008_add_num_partidas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField(blank=True)),
                ('fecha_finalizacion', models.DateTimeField()),
                ('finalizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuenta_gastos_finalizadas', to=settings.AUTH_USER_MODEL)),
                ('referencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_gastos', to='referencias.referencia')),
            ],
            options={
                'verbose_name': 'Cuenta de gastos',
                'verbose_name_plural': 'Cuentas de gastos',
                'ordering': ['-fecha_finalizacion'],
            },
        ),
    ]
