# Generated by Django 6.0.5 on 2026-08-18 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0010_add_fecha_captura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doda', models.IntegerField(db_index=True, unique=True)),
                ('num_doda', models.CharField(blank=True, max_length=34)),
                ('patente', models.CharField(db_index=True, max_length=10)),
                ('cve_caat', models.CharField(blank=True, db_index=True, max_length=6)),
                ('cve_capt', models.CharField(blank=True, max_length=20)),
                ('terminal_cve', models.CharField(blank=True, max_length=4)),
                ('terminal_nombre', models.CharField(blank=True, max_length=70)),
                ('fecha_doda', models.DateTimeField(blank=True, null=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('notificado_en', models.DateTimeField(blank=True, null=True)),
                ('modulacion_enviada_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cve_caat', 'fecha_baja'], name='referencias_cve_caa_854037_idx')],
            },
        ),
        migrations.CreateModel(
            name='DodaReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_refe', models.CharField(max_length=15)),
                ('cons_id', models.IntegerField()),
                ('doda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_doda', to='referencias.doda')),
                ('referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dodas', to='referencias.referencia')),
            ],
            options={
                'unique_together': {('doda', 'cons_id')},
            },
        ),
    ]
