# Generated by Django 6.0.5 on 2026-08-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0011_doda_dodareferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='peso_bruto',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
