# Generated by Django 6.0.5 on 2026-08-18 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0012_referencia_peso_bruto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioModulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=10)),
                ('push_estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=10)),
                ('sg_message_id', models.CharField(blank=True, max_length=100)),
                ('error_detalle', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_modulacion', to='referencias.doda')),
            ],
            options={
                'verbose_name': 'Envío de modulación',
                'verbose_name_plural': 'Envíos de modulación',
                'ordering': ['-created_at'],
            },
        ),
    ]
