# Generated by Django 6.0.5 on 2026-08-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0013_enviomodulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='doda',
            name='baj_doda',
            field=models.CharField(blank=True, db_index=True, max_length=34),
        ),
    ]
