# Generated by Django 6.0.5 on 2026-09-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0014_doda_baj_doda'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviomodulacion',
            name='links_completar',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
