# Generated by Django 6.0.5 on 2026-05-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('recibe_semanal', models.BooleanField(default=True)),
                ('recibe_mensual', models.BooleanField(default=True)),
                ('notas', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Destinatario',
                'verbose_name_plural': 'Destinatarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=10)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('destinatarios', models.TextField(help_text='JSON con lista de correos')),
                ('exitoso', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Historial de Reporte',
                'verbose_name_plural': 'Historial de Reportes',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
