# Generated by Django 6.0.5 on 2026-05-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatario',
            name='recibe_wa_mensual',
            field=models.BooleanField(default=False, verbose_name='WA Mensual'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='recibe_wa_semanal',
            field=models.BooleanField(default=False, verbose_name='WA Semanal'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Número internacional sin + (ej. 5217535342088)', max_length=20),
        ),
    ]
