# Generated by Django 6.0.5 on 2026-06-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_destinatario_recibe_wa_mensual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatario',
            name='recibe_wa_ia_cuenta_gastos',
            field=models.BooleanField(default=False, verbose_name='WA IA Cuenta Gastos'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='recibe_wa_ia_glosa',
            field=models.BooleanField(default=False, verbose_name='WA IA Glosa'),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='recibe_wa_ia_referencias',
            field=models.BooleanField(default=False, verbose_name='WA IA Referencias'),
        ),
    ]
