# Generated by Django 6.0.5 on 2026-05-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('out', 'Saliente'), ('in', 'Entrante')], max_length=3)),
                ('chat_id', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(default='sent', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('referencia_bot', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
