# Generated by Django 6.0.5 on 2026-06-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=255, unique=True)),
                ('cve_cliente', models.CharField(blank=True, max_length=20)),
                ('rfc', models.CharField(blank=True, max_length=13)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_cliente'],
            },
        ),
    ]
