# Generated by Django 6.0.5 on 2026-07-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email_cobranza',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_cobranza_cc',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
