# Generated by Django 6.0.5 on 2026-07-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_email_cobranza'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email_cuenta_gastos',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_cuenta_gastos_cc',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
